name: dev-ci

on:
    push:
        branches: ["main"]

    pull_request:
        branches: ["dev"]

jobs:
    Build-source:
        name: Build the project
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [20.18.1]

        steps:
            - name: Checkout to the source code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Try to build
              run: npm run build --if-presents
